//-----------------------------------------------------
//             Variables globales 
//-----------------------------------------------------
var productos = [
    { nombre: 'Escritorio Benalmadena',        precio: 125.000, stock: 12, marca:'Roble',    categoria: 'Escritorios', desCorta: 'Producto artesanal', desLarga: 'Estilo industrial y está fabricado con madera maciza de pino recuperada.',   edadDesde: '5', edadHasta: '99', foto: src="./img/Productos/escritorio-benalmadena.webp",     envio: false },
    { nombre: 'Escritorio Murcia con Cajones', precio: 185.000, stock: 5, marca:'Pino',      categoria: 'Escritorios', desCorta: 'Producto artesanal', desLarga: 'Escritorio rústico con dos cajones. Hermosa combinacion de colores de maderas duras recuperadas',               edadDesde: '5', edadHasta: '99',  foto: src="./img/Productos/escritorio-murcia.webp",     envio: true },
    { nombre: 'Recibidor Rústico Amelia',      precio: 115.000, stock: 8, marca:'Laurel',    categoria: 'Recibidores', desCorta: 'Producto artesanal', desLarga: 'Mueble Recibidor de Madera con dos cajones y detalle en X: Estilo Farmhouse y Funcionalidad. Bandeja inferior para adornos.',               edadDesde: '5', edadHasta: '99', foto: src="./img/Productos/recibidor-rustico-de-madera-con-gavetas.webp",     envio: true },
    { nombre: 'Macetero Estepona',             precio: 85.000,  stock: 25, marca:'Saligna',  categoria: 'Maceteros',   desCorta: 'Producto artesanal', desLarga: 'Hecho de madera de palets con diseño funcional, y ayuda a proteger las plantas de la lluvia o la humedad. Las ruedas permiten que se desplace fácilmente y admite todo tipo de plantas.',              edadDesde: '5', edadHasta: '99',  foto: src="./img/Productos/jardinera-2-1.webp",     envio: false },
    { nombre: 'Jardinera Casita',              precio: 85.000,  stock: 15, marca:'Saligna',  categoria: 'Maceteros',   desCorta: 'Producto artesanal', desLarga: 'Jardinera estilo casita de madera diseñada para ser resistente a la vez bonita y funcional. El cuidado y altos estándares de calidad en nuestros productos hacen que sea fácil adaptarlas tanto en interiores como exteriores.',              edadDesde: '5', edadHasta: '99',  foto: src="./img/Productos/jardinera-3.webp",     envio: false },
    { nombre: 'Macetero Huelva',               precio: 75.000,  stock: 35, marca:'Saligna',  categoria: 'Maceteros',   desCorta: 'Producto artesanal', desLarga: 'Macetero de madera y jardinera exterior para macetas. Cómodo y práctico, este macetero de madera no sólo te ayudará a mantener en su lugar las plantas que tienes en la terraza, sino que además se convertirá en un acogedor elemento decorativo.',              edadDesde: '5', edadHasta: '99',  foto: src="./img/Productos/macetero-huelva.webp",     envio: false },
]

